plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - "README.md"
    - "docs/**/*"
    - "doc/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "tmp/**/*"
    - "db/schema.rb"
    - "db/queue_schema.rb"
    - "db/migrate/**/*"

Style/Documentation:
  Enabled: false
